const exactTemplateNames: Record<string, string> = {
  "Product Manager": "产品经理",
  "Software Architect": "软件架构师",
  "Frontend Engineer": "前端工程师",
  "Code Reviewer": "代码审查员",
  "Growth Strategist": "增长策略师",
  "Anthropologist": "人类学顾问",
  "Geographer": "地理学顾问",
  "Historian": "历史学顾问",
  "Narratologist": "叙事学顾问",
  "Psychologist": "心理学顾问",
  "Brand Guardian": "品牌守护者",
  "Image Prompt Engineer": "图像提示词工程师",
  "Inclusive Visuals Specialist": "包容性视觉专家",
  "Persona Walkthrough Specialist": "用户画像走查专家",
  "UI Designer": "UI 设计师",
  "UX Architect": "UX 架构师",
  "UX Researcher": "UX 研究员",
  "Visual Storyteller": "视觉叙事师",
  "Whimsy Injector": "趣味创意师",
  "AI Data Remediation Engineer": "AI 数据修复工程师",
  "AI Engineer": "AI 工程师",
  "Autonomous Optimization Architect": "自动优化架构师",
  "Backend Architect": "后端架构师",
  "CMS Developer": "CMS 开发工程师",
  "Codebase Onboarding Engineer": "代码库导览工程师",
  "Data Engineer": "数据工程师",
  "Database Optimizer": "数据库优化工程师",
  "DevOps Automator": "DevOps 自动化工程师",
  "Drupal Shopping Cart Engineer": "Drupal 购物车工程师",
  "Email Intelligence Engineer": "邮件智能工程师",
  "Embedded Firmware Engineer": "嵌入式固件工程师",
  "Feishu Integration Developer": "飞书集成开发工程师",
  "Filament Optimization Specialist": "Filament 优化专家",
  "Frontend Developer": "前端开发工程师",
  "Git Workflow Master": "Git 工作流专家",
  "Incident Response Commander": "事故响应指挥官",
  "IT Service Manager": "IT 服务经理",
  "Minimal Change Engineer": "最小变更工程师",
  "Mobile App Builder": "移动应用构建工程师",
  "Multi-Agent Systems Architect": "多智能体系统架构师",
  "OrgScript Engineer": "OrgScript 工程师",
  "Prompt Engineer": "提示词工程师",
  "Rapid Prototyper": "快速原型工程师",
  "Senior Developer": "高级开发工程师",
  "Solidity Smart Contract Engineer": "Solidity 智能合约工程师",
  "SRE (Site Reliability Engineer)": "SRE 站点可靠性工程师",
  "Technical Writer": "技术文档工程师",
  "Voice AI Integration Engineer": "语音 AI 集成工程师",
  "WeChat Mini Program Developer": "微信小程序开发工程师",
  "WordPress Shopping Cart Engineer": "WordPress 购物车工程师",
  "Bookkeeper & Controller": "记账与财务控制专员",
  "Financial Analyst": "财务分析师",
  "FP&A Analyst": "FP&A 分析师",
  "Investment Researcher": "投资研究员",
  "Tax Strategist": "税务策略师",
  "Blender Add-on Engineer": "Blender 插件工程师",
  "Game Audio Engineer": "游戏音频工程师",
  "Game Designer": "游戏设计师",
  "Godot Gameplay Scripter": "Godot 玩法脚本工程师",
  "Godot Multiplayer Engineer": "Godot 多人游戏工程师",
  "Godot Shader Developer": "Godot 着色器开发工程师",
  "Level Designer": "关卡设计师",
  "Narrative Designer": "叙事设计师",
  "Roblox Avatar Creator": "Roblox 头像创作者",
  "Roblox Experience Designer": "Roblox 体验设计师",
  "Roblox Systems Scripter": "Roblox 系统脚本工程师",
  "Technical Artist": "技术美术",
  "Unity Architect": "Unity 架构师",
  "Unity Editor Tool Developer": "Unity 编辑器工具开发工程师",
  "Unity Multiplayer Engineer": "Unity 多人游戏工程师",
  "Unity Shader Graph Artist": "Unity Shader Graph 美术",
  "Unreal Multiplayer Architect": "Unreal 多人游戏架构师",
  "Unreal Systems Engineer": "Unreal 系统工程师",
  "Unreal Technical Artist": "Unreal 技术美术",
  "Unreal World Builder": "Unreal 世界构建师",
  "3D & Scene Developer": "3D 与场景开发工程师",
  "GIS Analyst": "GIS 分析师",
  "BIM/GIS Specialist": "BIM/GIS 专家",
  "Cartography Designer": "制图设计师",
  "Drone/Reality Mapping Specialist": "无人机与实景建图专家",
  "GeoAI/ML Engineer": "GeoAI/机器学习工程师",
  "Geoprocessing Specialist": "地理处理专家",
  "GIS QA Engineer": "GIS 测试工程师",
  "Solution Engineer": "解决方案工程师",
  "Spatial Data Engineer": "空间数据工程师",
  "Spatial Data Scientist": "空间数据科学家",
  "Technical Consultant": "技术顾问",
  "Web GIS Developer": "Web GIS 开发工程师",
  "AEO Foundations Architect": "AEO 基础架构师",
  "Agentic Search Optimizer": "智能体搜索优化师",
  "AI Citation Strategist": "AI 引用策略师",
  "App Store Optimizer": "应用商店优化师",
  "Baidu SEO Specialist": "百度 SEO 专家",
  "Bilibili Content Strategist": "B 站内容策略师",
  "Book Co-Author": "图书合著顾问",
  "Carousel Growth Engine": "轮播内容增长专家",
  "China E-Commerce Operator": "中国电商运营",
  "China Market Localization Strategist": "中国市场本地化策略师",
  "Content Creator": "内容创作者",
  "Cross-Border E-Commerce Specialist": "跨境电商专家",
  "Douyin Strategist": "抖音策略师",
  "Email Marketing Strategist": "邮件营销策略师",
  "Global Podcast Strategist": "全球播客策略师",
  "Growth Hacker": "增长黑客",
  "Instagram Curator": "Instagram 内容策展人",
  "Kuaishou Strategist": "快手策略师",
  "LinkedIn Content Creator": "LinkedIn 内容创作者",
  "Livestream Commerce Coach": "直播电商教练",
  "Multi-Platform Publisher": "多平台发布运营",
  "Podcast Strategist": "播客策略师",
  "PR & Communications Manager": "公关与传播经理",
  "Private Domain Operator": "私域运营",
  "Reddit Community Builder": "Reddit 社区运营",
  "SEO Specialist": "SEO 专家",
  "Short-Video Editing Coach": "短视频剪辑教练",
  "Social Media Strategist": "社交媒体策略师",
  "TikTok Strategist": "TikTok 策略师",
  "Twitter Engager": "Twitter 互动运营",
  "Video Optimization Specialist": "视频优化专家",
  "WeChat Official Account Manager": "微信公众号运营",
  "Weibo Strategist": "微博策略师",
  "X/Twitter Intelligence Analyst": "X/Twitter 情报分析师",
  "Xiaohongshu Specialist": "小红书专家",
  "Zhihu Strategist": "知乎策略师",
  "Paid Media Auditor": "付费媒体审计师",
  "Ad Creative Strategist": "广告创意策略师",
  "Paid Social Strategist": "付费社交策略师",
  "PPC Campaign Strategist": "PPC 投放策略师",
  "Programmatic & Display Buyer": "程序化与展示广告采购",
  "Search Query Analyst": "搜索词分析师",
  "Tracking & Measurement Specialist": "追踪与衡量专家",
  "Behavioral Nudge Engine": "行为助推专家",
  "Feedback Synthesizer": "反馈综合分析师",
  "Sprint Prioritizer": "Sprint 优先级规划师",
  "Trend Researcher": "趋势研究员",
  "Experiment Tracker": "实验跟踪员",
  "Jira Workflow Steward": "Jira 工作流管理员",
  "Meeting Notes Specialist": "会议纪要专家",
  "Project Shepherd": "项目推进经理",
  "Studio Operations": "工作室运营",
  "Studio Producer": "工作室制片人",
  "Senior Project Manager": "高级项目经理",
  "Account Strategist": "客户策略师",
  "Sales Coach": "销售教练",
  "Deal Strategist": "交易策略师",
  "Discovery Coach": "需求发现教练",
  "Sales Engineer": "售前工程师",
  "Offer & Lead Gen Strategist": "报价与线索生成策略师",
  "Outbound Strategist": "外呼拓展策略师",
  "Pipeline Analyst": "销售管道分析师",
  "Proposal Strategist": "方案策略师",
  "Application Security Engineer": "应用安全工程师",
  "Security Architect": "安全架构师",
  "Blockchain Security Auditor": "区块链安全审计师",
  "Cloud Security Architect": "云安全架构师",
  "Compliance Auditor": "合规审计师",
  "Incident Responder": "安全事件响应工程师",
  "Penetration Tester": "渗透测试工程师",
  "Senior SecOps Engineer": "高级安全运营工程师",
  "Threat Detection Engineer": "威胁检测工程师",
  "Threat Intelligence Analyst": "威胁情报分析师",
  "macOS Spatial/Metal Engineer": "macOS 空间与 Metal 工程师",
  "Terminal Integration Specialist": "终端集成专家",
  "visionOS Spatial Engineer": "visionOS 空间工程师",
  "XR Cockpit Interaction Specialist": "XR 座舱交互专家",
  "XR Immersive Developer": "XR 沉浸式开发工程师",
  "XR Interface Architect": "XR 界面架构师",
  "Accounts Payable Agent": "应付账款专员",
  "Agentic Identity & Trust Architect": "智能体身份与信任架构师",
  "Agents Orchestrator": "智能体编排师",
  "Automation Governance Architect": "自动化治理架构师",
  "Business Strategist": "商业策略师",
  "Change Management Consultant": "变革管理顾问",
  "Chief Financial Officer": "首席财务官",
  "Corporate Training Designer": "企业培训设计师",
  "Customer Service": "客户服务专员",
  "Customer Success Manager": "客户成功经理",
  "Data Consolidation Agent": "数据整合专员",
  "Data Privacy Officer": "数据隐私官",
  "ESG & Sustainability Officer": "ESG 与可持续发展官",
  "Government Digital Presales Consultant": "政务数字化售前顾问",
  "Grant Writer": "资助申请撰写顾问",
  "Healthcare Customer Service": "医疗客户服务专员",
  "Healthcare Marketing Compliance Specialist": "医疗营销合规专家",
  "Hospitality Guest Services": "酒店宾客服务专员",
  "HR Onboarding": "HR 入职专员",
  "Identity Graph Operator": "身份图谱运营",
  "Language Translator": "语言翻译",
  "Legal Billing & Time Tracking": "法务账单与工时跟踪专员",
  "Legal Client Intake": "法务客户接待专员",
  "Legal Document Review": "法务文档审查员",
  "Loan Officer Assistant": "贷款专员助理",
  "LSP/Index Engineer": "LSP/索引工程师",
  "M&A Integration Manager": "并购整合经理",
  "Medical Billing & Coding Specialist": "医疗账单与编码专家",
  "Operations Manager": "运营经理",
  "Organizational Psychologist": "组织心理学顾问",
  "Personal Growth Mentor": "个人成长导师",
  "Real Estate Buyer & Seller": "房产买卖顾问",
  "Recruitment Specialist": "招聘专家",
  "Report Distribution Agent": "报告分发专员",
  "Retail Customer Returns": "零售退货专员",
  "Sales Data Extraction Agent": "销售数据提取专员",
  "Sales Outreach": "销售拓展专员",
  "Chief of Staff": "幕僚长",
  "Civil Engineer": "土木工程师",
  "Cultural Intelligence Strategist": "文化智能策略师",
  "Developer Advocate": "开发者关系顾问",
  "Document Generator": "文档生成专员",
  "French Consulting Market Navigator": "法国咨询市场导航顾问",
  "Korean Business Navigator": "韩国商务导航顾问",
  "MCP Builder": "MCP 构建工程师",
  "Model QA Specialist": "模型质量测试专家",
  "Pricing Analyst": "定价分析师",
  "Salesforce Architect": "Salesforce 架构师",
  "Strategy Duel Agent": "策略辩论顾问",
  "Workflow Architect": "工作流架构师",
  "Study Abroad Advisor": "留学顾问",
  "Supply Chain Strategist": "供应链策略师",
  "ZK Steward": "ZK 治理专员",
  "Analytics Reporter": "数据分析报告员",
  "Executive Summary Generator": "高管摘要生成专员",
  "Finance Tracker": "财务跟踪员",
  "Infrastructure Maintainer": "基础设施维护工程师",
  "Legal Compliance Checker": "法务合规审查员",
  "Support Responder": "支持响应专员",
  "Accessibility Auditor": "无障碍审计师",
  "API Tester": "API 测试工程师",
  "Evidence Collector": "证据收集员",
  "Performance Benchmarker": "性能基准测试员",
  "Reality Checker": "真实性核查员",
  "Test Results Analyzer": "测试结果分析师",
  "Tool Evaluator": "工具评估员",
  "Workflow Optimizer": "工作流优化师",
  "Douyin Operations Analyst": "抖音运营分析师",
  "Builder AI": "开发工程师",
  "QA AI": "测试工程师",
  "Product AI": "产品验收员",
  "Release AI": "发布管理员"
};

export function localizeTemplateName(name: string): string {
  const normalized = String(name || "").trim();
  return exactTemplateNames[normalized] || normalized;
}

export function aiEmployeeTitleForTemplate(name: string): string {
  const localizedName = localizeTemplateName(name);
  return localizedName.startsWith("AI ") ? localizedName : `AI ${localizedName}`;
}
